---
- name: "Installing {{ item }}"
  package:
   name: "{{ item }}"
  with_items:
   - apache2
   - php
   - mysql-server
   - libapache2-mod-php
   - php-mysql
   - python-mysqldb
  register: status

- name: restart apache2
  service:
   name: apache2
   state: restarted
  when: status.changed
